---
- name: Install NFS server package
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: present
    update_cache: true
  become: true

- name: Configure NFS exports
  ansible.builtin.template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: Reload NFS exports

- name: Ensure NFS server is started and enabled
  ansible.builtin.service:
    name: nfs-kernel-server
    state: started
    enabled: true
  become: true
