# cleanup-playbook.yml
- name: Tear down KVM VMs
  hosts: localhost
  gather_facts: false
  vars_files:
    - roles/kvm_ubuntu_vm/defaults/main.yml
  tasks:
    - name: Run cleanup logic from role
      include_role:
        name: kvm_ubuntu_vm
        tasks_from: cleanup.yml
      loop: "{{ kvm_vms }}"
      loop_control:
        loop_var: vm
      vars:
        vm: "{{ vm }}"
