---
- name: Ensure casparcg user exists
  ansible.builtin.user:
    name: "{{ casparcg_user }}"
    shell: /usr/sbin/nologin
    system: true
  become: true

- name: Install nodm package
  ansible.builtin.apt:
    name: nodm
    state: present
    update_cache: true
  become: true

- name: Install CasparCG CEF package from URL
  ansible.builtin.apt:
    deb: "{{ casparcg_cef_url }}"
    state: present
    update_cache: false
    install_recommends: false
  become: true

- name: Install CasparCG Server package from URL
  ansible.builtin.apt:
    deb: "{{ casparcg_server_url }}"
    state: present
    update_cache: false
    install_recommends: false
  become: true

- name: Configure nodm
  ansible.builtin.template:
    src: nodm.conf.j2
    dest: "/etc/default/nodm"
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Render casparcg.config to /etc
  ansible.builtin.template:
    src: "casparcg.config.j2"
    dest: "/etc/casparcg.config"
    owner: root
    group: root
    mode: '0644'
  become: true


- name: Ensure nodm service is started and enabled
  ansible.builtin.service:
    name: nodm
    state: started
    enabled: true
  become: true
