---
- name: Ensure namespace exists
  become: true
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ cnpg_cluster_namespace }}"
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"

- name: Create app user secret
  become: true
  no_log: true
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'app-secret.yml.j2') }}"
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"

- name: Create superuser secret
  become: true
  no_log: true
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'superuser-secret.yml.j2') }}"
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"

- name: Deploy CloudNativePG Cluster
  become: true
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'cluster.yml.j2') }}"
    state: present
    kubeconfig: "{{ k8s_kubeconfig }}"
