---
netboot_file: "ubuntu-24.04.2-netboot-amd64.tar.gz"
netboot_url: "https://releases.ubuntu.com/noble/{{ netboot_file }}"
# Replace with the real SHA256 of that tarball
netboot_checksum: "sha256:d7fe3d6a0419667d2f8eff12796996328daa2d4f90cd9f87aa9371b362f987bf"

# Where to put PXE/TFTP files
tftp_root: /var/lib/tftpboot

# Where to serve autoinstall user-data
http_root: /var/www/html
http_base_url: "http://{{ ansible_fqdn }}/autoinstall"

