---
- name: Add users to system
  hosts: all
  become: true
  gather_facts: false
  roles:
    - users
  tags: common
- name: Install VM guest packages
  hosts: qemu_guest
  become: true
  gather_facts: false
  roles:
    - qemu_guest
  tags: common
