---
- name: Add users to system
  hosts: all
  become: true
  gather_facts: true
  roles:
    - users
  tags: common
- name: Do common setup
  hosts: all
  become: true
  gather_facts: true
  roles:
    - common
  tags: common
- name: Install VM guest packages
  hosts: qemu_guest
  become: true
  gather_facts: false
  roles:
    - qemu_guest
  tags: common
- name: Configure DNS server
  hosts: util
  roles:
    - freebsd
    - dns_server
