- name: Install keepalived
  apt:
    name: keepalived
    state: present

- name: Configure keepalived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: '0644'

- name: Ensure custom routing table exists
  lineinfile:
    path: /etc/iproute2/rt_tables
    line: "100 vipwan"
    create: yes
    state: present
    regexp: '^100\s+vipwan'

- name: Get current default route in vipwan table
  command: ip route show table vipwan
  register: vipwan_routes
  changed_when: false

- name: Set current default gateway fact (if present)
  set_fact:
    current_vipwan_gateway: "{{ vipwan_routes.stdout_lines | select('search', '^default ') | map('regex_replace', '^default via ([^ ]+).*', '\\1') | list | first | default('') }}"

- name: Update default route in vipwan table if needed
  command: >
    ip route replace default via {{ keepalived_gateway }}
    dev {{ keepalived_interface }} table vipwan
  when: current_vipwan_gateway != keepalived_gateway

- name: Get current IP rules
  command: ip rule show
  register: ip_rules
  changed_when: false

- name: Check if VIP rule exists
  set_fact:
    vip_rule_exists: "{{ ('from ' ~ keepalived_vip ~ '/32 lookup vipwan') in ip_rules.stdout }}"

- name: Add IP rule for VIP if not present
  command: >
    ip rule add from {{ keepalived_vip }}/32 table vipwan priority 20000
  when: not vip_rule_exists

- name: Enable and restart keepalived
  systemd:
    name: keepalived
    enabled: true
    state: restarted

