- name: Stop VM if running - {{ vm.name }}
  community.libvirt.virt:
    name: "{{ vm.name }}"
    command: "destroy"

- name: Undefine VM {{ vm.name }}
  command: "virsh undefine {{ vm.name }} --remove-all-storage"
  ignore_errors: true

- name: Remove VM disk
  file:
    path: "/var/lib/libvirt/images/{{ vm.name }}.qcow2"
    state: absent
  ignore_errors: true

- name: Remove cloud-init ISO
  file:
    path: "/var/lib/libvirt/images/{{ vm.name }}-seed.iso"
    state: absent
  ignore_errors: true

