- debug:
    msg: "Looping over {{ item }}"
  loop: "{{ kvm_vms }}"
- name: Ensure base image is downloaded
  get_url:
    url: "https://cloud-images.ubuntu.com/{{ ubuntu_release }}/current/{{ ubuntu_release }}-server-cloudimg-amd64.img"
    dest: "/var/lib/libvirt/images/{{ ubuntu_release }}-base.qcow2"
    mode: '0644'

- name: Provision and start all defined VMs
  include_tasks: vm.yml
  loop: "{{ kvm_vms }}"
  loop_control:
    loop_var: vm
