- name: DEBUG current vm item
  debug:
    msg: "Provisioning {{ vm.name }}"

- name: Include cloud-init tasks for {{ vm.name }}
  include_tasks: cloudinit.yml

- name: Create VM disk for {{ vm.name }}
  command: >
    qemu-img create -f qcow2 -F qcow2 -b /var/lib/libvirt/images/{{ ubuntu_release }}-base.qcow2
    /var/lib/libvirt/images/{{ vm.name }}.qcow2
    {{ vm.disk_size | default(default_disk_size) }}G
  args:
    creates: "/var/lib/libvirt/images/{{ vm.name }}.qcow2"

- name: Define libvirt domain for {{ vm.name }}
  community.libvirt.virt:
    command: define
    xml: "{{ lookup('template', 'domain.xml.j2') }}"

- name: Start the VM {{ vm.name }}
  community.libvirt.virt:
    name: "{{ vm.name }}"
    state: running
