---
- name: Install DHCP/TFTP/HTTP services
  apt:
    name:
      - dnsmasq
      - tftpd-hpa
      - apache2
    state: present
    update_cache: yes

- name: Create TFTP root directory
  file:
    path: "{{ tftp_root }}"
    state: directory

- name: Download Ubuntu netboot archive
  get_url:
    url: "{{ netboot_url }}"
    dest: "{{ tftp_root }}/{{ netboot_file }}"
    checksum: "{{ netboot_checksum }}"

- name: Extract netboot files
  unarchive:
    src: "{{ tftp_root }}/{{ netboot_file }}"
    dest: "{{ tftp_root }}/"
    remote_src: yes

- name: Ensure HTTP directory for autoinstall exists
  file:
    path: "{{ http_root }}/autoinstall"
    state: directory

- name: Deploy autoinstall YAMLs
  loop: "{{ machines | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  template:
    src: autoinstall.yaml.j2
    dest: "{{ http_root }}/autoinstall/{{ item.key }}.yaml"

- name: Deploy dnsmasq configuration
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.d/pxe.conf
  notify: Restart dnsmasq

- name: Restart dnsmasq
  listen: Restart dnsmasq
  service:
    name: dnsmasq
    state: restarted

