---
- name: Install Kubegres operator
  kubernetes.core.k8s:
    kubeconfig: "{{ k8s_kubeconfig }}"
    state: present
    src: "{{ kubegres_manifest_url }}"
  become: true
  run_once: true

- name: Wait for Kubegres controller to be ready
  kubernetes.core.k8s_info:
    kubeconfig: "{{ k8s_kubeconfig }}"
    kind: Deployment
    namespace: kubegres-system
    name: kubegres-controller-manager
    wait: true
    wait_condition:
      type: Available
      status: "True"
    wait_timeout: 120
  become: true
  run_once: true
