---
- name: Deploy Schedule Service via ArgoCD Application
  become: true
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'application.yml.j2') }}"
    state: present
    kubeconfig: "{{ argocd_kubeconfig }}"

- name: Deploy Schedule Service Argo CD Image Updater tracking
  become: true
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'image-updater.yml.j2') }}"
    state: present
    kubeconfig: "{{ argocd_kubeconfig }}"
  when: argocd_image_updater_enabled | bool
